services:
  server:
    container_name: zst-converter
    build: .
    expose:
      - 5000
    networks:
      - proxy
    restart: unless-stopped
    volumes: 
      - .:/app
    logging:
      driver: syslog
      options:
        tag: 'zst-converter'

networks:
  proxy:
    name: npm-proxy
    external: true
